### PR TITLE
Opt ssl read log

### PR DESCRIPTION
**Pull request by chenBright**
### What problem does this PR solve?

Issue Number: #977

Problem Summary:

对端发送完数据后关闭连接或者shutdown ssl，就有可能出现ssl_error=SSL_ERROR_SYSCALL/SSL_ERROR_ZERO_RETURN、nr>0、e=0，这应该是正常情况，没有必要打印WARNING日志。

### What is changed and the side effects?

Changed:

Side effects:
- Performance effects(性能影响):

- Breaking backward compatibility(向后兼容性): 

---
### Check List:
- Please make sure your changes are compilable(请确保你的更改可以通过编译).
- When providing us with a new feature, it is best to add related tests(如果你向我们增加一个新的功能, 请添加相关测试).
- Please follow [Contributor Covenant Code of Conduct](../../master/CODE_OF_CONDUCT.md).(请遵循贡献者准则).

### CODE REVIEW

**Comment by Huixxi** [comment]
SSL_ERROR_SYSCALL 这个也要忽略么？

**Comment by chenBright** [comment]
[SSL_read](https://linux.die.net/man/3/ssl_get_error)文档中提到，这个场景只是读到EOF而已，不算是错误。
> SSL_ERROR_SYSCALL
Some I/O error occurred. The OpenSSL error queue may contain more information on the error. If the error queue is empty (i.e. ERR_get_error() returns 0), ret can be used to find out more about the error: If ret == 0, an EOF was observed that violates the protocol. If ret == -1, the underlying BIO reported an I/O error (for socket I/O on Unix systems, consult errno for details).

**Comment by Huixxi** [comment]
> [SSL_read](https://linux.die.net/man/3/ssl_get_error)文档中提到，这个场景只是读到EOF而已，不算是错误。
> 
> > SSL_ERROR_SYSCALL
> > Some I/O error occurred. The OpenSSL error queue may contain more information on the error. If the error queue is empty (i.e. ERR_get_error() returns 0), ret can be used to find out more about the error: If ret == 0, an EOF was observed that violates the protocol. If ret == -1, the underlying BIO reported an I/O error (for socket I/O on Unix systems, consult errno for details).

EOF只是ret==0的时候吧，ret==-1的时候该怎么判断呢？

**Comment by wwbmmm** [comment]
LGTM

**Pull request merged**
