### PR TITLE
fix h2 rpc_dump memory leak bug

### PR DESCRIPTION
**Pull request by GreateCode**
### What problem does this PR solve?

Issue Number:

Problem Summary:
**h2 rpc_dump时 内存泄漏**。

具体是http和h2都走ProcessHttpRequest方法，在处理rpc_dump时，先AskToBeSampled创建堆对象再判is_http2，若是http2无释放堆对象逻辑。

发压cmd：rpc_press -protocol=h2 xxxx

### What is changed and the side effects?
Changed:
h2 req不做AskToBeSampled

修复前：
image
image
image
image

[brpc_h2_rpc_dump_mem_leak_bug.pdf](https://github.com/user-attachments/files/15798428/brpc_h2_rpc_dump_mem_leak_bug.pdf)

修复后：
image
image
image

[brpc_h2_rpc_dump_mem_leak_fixed.pdf](https://github.com/user-attachments/files/15798432/brpc_h2_rpc_dump_mem_leak_fixed.pdf)

Side effects:
- Performance effects(性能影响):
无
- Breaking backward compatibility(向后兼容性): 

---
### Check List:
- Please make sure your changes are compilable(请确保你的更改可以通过编译).
- When providing us with a new feature, it is best to add related tests(如果你向我们增加一个新的功能, 请添加相关测试).
- Please follow [Contributor Covenant Code of Conduct](../../master/CODE_OF_CONDUCT.md).(请遵循贡献者准则).

### CODE REVIEW

**Comment by GreateCode** [comment]
@chenBright

**Review by chenBright — APPROVED** [review]
LGTM

**Comment by GreateCode** [comment]
@wwbmmm 合下？

**Comment by yanglimingcn** [comment]
LGTM

**Pull request merged**
