### PR TITLE
Set http default method to "/"

### PR DESCRIPTION
**Pull request by chenBright**
### What problem does this PR solve?

Issue Number:

Problem Summary:

### What is changed and the side effects?

Changed:

Side effects:
- Performance effects(性能影响):

- Breaking backward compatibility(向后兼容性): 

---
### Check List:
- Please make sure your changes are compilable(请确保你的更改可以通过编译).
- When providing us with a new feature, it is best to add related tests(如果你向我们增加一个新的功能, 请添加相关测试).
- Please follow [Contributor Covenant Code of Conduct](../../master/CODE_OF_CONDUCT.md).(请遵循贡献者准则).

### CODE REVIEW

**Comment by wwbmmm** [comment]
这个是否会影响代码的向前兼容性？

**Comment by chenBright** [comment]
应该不影响，目前method name只在创建client span的时候使用了而已。
https://github.com/apache/brpc/blob/fc885ad37d5a1dfae47f1a32d899569b55376dab/src/brpc/channel.cpp#L470-L479

**Comment by chenBright** [comment]
如果担心有影响的话，也可以在CallMethod中，_get_method_name后method_name为空再设置为"/"。

**Comment by wwbmmm** [comment]
LGTM

**Pull request merged**
